DELETE FROM KLIENT WHERE IDKLIENT > 0
DELETE FROM PRACOWNIK WHERE IDPRACOWNIK > 0
DELETE FROM PROGRAMISTA WHERE IDPRACOWNIK > 0
DELETE FROM POZYCJONER WHERE IDPRACOWNIK > 0
DELETE FROM TESTER WHERE IDPRACOWNIK > 0
DELETE FROM GRAFIK WHERE IDPRACOWNIK > 0
DELETE FROM SZEF WHERE IDPRACOWNIK > 0
DELETE FROM OSOBA WHERE IDOSOBA > 0
DBCC CHECKIDENT ('OSOBA', RESEED, 0)
GO